<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>library_app</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\1984.jpg" />
    <None Remove="images\alien.jpg" />
    <None Remove="images\appetitefordestruction.jpg" />
    <None Remove="images\backinblack.jpg" />
    <None Remove="images\bladerunner.jpg" />
    <None Remove="images\ciberpun.jpg" />
    <None Remove="images\darksouls.jpg" />
    <None Remove="images\donqujotedelamancha.jpg" />
    <None Remove="images\doometernal.jpg" />
    <None Remove="images\dune.jpg" />
    <None Remove="images\eldenring.jpg" />
    <None Remove="images\gladiator.jpg" />
    <None Remove="images\godofwar.jpg" />
    <None Remove="images\harrypotterstone.jpg" />
    <None Remove="images\hightwaytohell.jpg" />
    <None Remove="images\holydiver.jpg" />
    <None Remove="images\inception.jpg" />
    <None Remove="images\interstellar.jpg" />
    <None Remove="images\maincra.jpg" />
    <None Remove="images\masterofpuppets.jpg" />
    <None Remove="images\painkiller.jpg" />
    <None Remove="images\paranoid.jpg" />
    <None Remove="images\pulpfiction.jpg" />
    <None Remove="images\rdr2.jpg" />
    <None Remove="images\reigninblood.jpg" />
    <None Remove="images\spiritedaway.jpg" />
    <None Remove="images\thedarkknight.jpg" />
    <None Remove="images\thedarksideofthemoon.jpg" />
    <None Remove="images\thegodfather.jpg" />
    <None Remove="images\thehobbit.jpg" />
    <None Remove="images\thematrix.jpg" />
    <None Remove="images\thenameoftherose.jpg" />
    <None Remove="images\thenumberofthebeast.jpg" />
    <None Remove="images\theroad.jpg" />
    <None Remove="images\theshining.jpg" />
    <None Remove="images\thewitcherbloodofelves.jpg" />
    <None Remove="images\thewither3.jpg" />
    <None Remove="images\tlotr.jpg" />
    <None Remove="images\tlou.jpg" />
    <None Remove="images\zeldabotw.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Window1.xaml">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="images\1984.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\alien.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\appetitefordestruction.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\backinblack.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\bladerunner.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\ciberpun.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\darksouls.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\donqujotedelamancha.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\doometernal.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\dune.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\eldenring.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\gladiator.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\godofwar.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\harrypotterstone.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\hightwaytohell.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\holydiver.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\inception.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\interstellar.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\maincra.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\masterofpuppets.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\painkiller.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\paranoid.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\pulpfiction.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\rdr2.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\reigninblood.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\spiritedaway.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\thedarkknight.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\thedarksideofthemoon.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\thegodfather.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\thehobbit.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\thematrix.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\thenameoftherose.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\thenumberofthebeast.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\theroad.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\theshining.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\thewitcherbloodofelves.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\thewither3.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\tlotr.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\tlou.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="images\zeldabotw.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
